# Generated by Django 4.2.7 on 2025-08-16 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_system', '0002_alter_employee_options_alter_formfield_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='data',
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='placeholder@example.com', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='+0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{10,15}$')]),
        ),
    ]
