# Generated by Django 4.2.7 on 2025-08-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees_system', '0003_remove_employee_data_employee_address_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extra_data',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formfield',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
