# Generated by Django 5.2.6 on 2025-09-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees_system', '0004_employee_extra_data_formfield_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_data',
            field=models.JSONField(default=dict),
        ),
    ]
